services:
  vault:
    image: hashicorp/vault:1.15.3
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: devroot
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    command: "server -dev"

  redis:
    image: redis:7.4
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command:
      ["redis-server", "--requirepass", "redisPassword", "--appendonly", "yes"]

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    restart: always
    ports:
      - "5540:5540"

  vault-init:
    image: hashicorp/vault:1.15.3
    depends_on:
      - vault
    entrypoint: /bin/sh
    command: >
      -c "
      sleep 5 && 
      export VAULT_ADDR=http://vault:8200 &&
      export VAULT_TOKEN=devroot &&
      vault secrets enable transit &&
      vault write -f transit/keys/card-encryption-key
      "

  payment-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - payment-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: payment-demo
      POSTGRES_USER: payment-demo
      POSTGRES_PASSWORD: payment123

volumes:
  redis-data:
  payment-db-data:
