spring:
  application:
    name: payment-demo
  cloud:
    vault:
      uri: http://${VAULT_URI:localhost}:${VAULT_PORT:8200}
      token: ${VAULT_TOKEN:devroot}
      authentication: TOKEN
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:redisPassword}
    database: 0
    timeout: 2000ms
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:payment-demo}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:payment-demo}
    password: ${DB_PASSWORD:payment123}
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8443
  ssl:
    key-store: src/main/resources/secrets/keystore.p12
    key-store-password: pcidssdemo
    key-store-type: PKCS12
    key-alias: pcidssdemo

jwt:
  validity: 1800000
  pem-path: src/main/resources/secrets/private_key.pem
  public-pem-path: src/main/resources/secrets/public_key.pem

time:
  zone: "Europe/Istanbul"

encryption:
  key: card-encryption-key

allowed:
  origin: ${ALLOWED_ORIGIN:http://localhost:3000}

